(function(mdBone,$,undefined){"use strict";var Util={getBackendVar:function(variable_name){if(typeof window['mdBoneVar']==='undefined'){return '';}
if(arguments.length==1){return window['mdBoneVar'][variable_name];}else{var b=arguments[1];return window['mdBoneVar'][variable_name][b];}},moveY:function(elm,value){var translate='translate3d(0px,'+value+'px, 0)';elm.style['-webkit-transform']=translate;elm.style['-moz-transform']=translate;elm.style['-ms-transform']=translate;elm.style['-o-transform']=translate;elm.style.transform=translate;},};var EventsListener={scroll_event_slow_run:false,scroll_event_medium_run:false,resize_event_slow_run:false,resize_event_medium_run:false,scroll_window_scrollTop:0,window_innerHeight:window.innerHeight,window_innerWidth:window.innerWidth,init:function init(){var smartAffixOn=Util.getBackendVar('stickyHeader','toggle');$(window).scroll(function(){EventsListener.scroll_event_slow_run=true;EventsListener.scroll_event_medium_run=true;});$(window).resize(function(){EventsListener.resize_event_slow_run=true;EventsListener.resize_event_medium_run=true;});setInterval(function(){if(EventsListener.scroll_event_medium_run){EventsListener.scroll_event_medium_run=false;EventsListener.scroll_window_scrollTop=$(window).scrollTop();if(smartAffixOn=='1'){smartAffix.eventScroll(EventsListener.scroll_window_scrollTop);}}
if(EventsListener.resize_event_medium_run){EventsListener.resize_event_medium_run=false;if(smartAffixOn=='1'){smartAffix.compute();}}},10);setInterval(function(){if(EventsListener.scroll_event_slow_run){EventsListener.scroll_event_slow_run=false;}
if(EventsListener.resize_event_slow_run){EventsListener.resize_event_slow_run=false;Detect.run_is_phone_screen();}},500);}};EventsListener.init();var Detect=new function(){this.is_ie8=false;this.is_ie9=false;this.is_ie10=false;this.is_ie11=false;this.is_ie=false;this.is_safari=false;this.is_chrome=false;this.is_ipad=false;this.is_touch_device=false;this.has_history=false;this.is_phone_screen=false;this.is_ios=false;this.is_android=false;this.is_osx=false;this.is_firefox=false;this.is_touch_device=!!('ontouchstart'in window);this.is_mobile_device=false;this.html_jquery_obj=$('html');if(this.html_jquery_obj.is('.ie8')){this.is_ie8=true;this.is_ie=true;}
if(this.html_jquery_obj.is('.ie9')){this.is_ie9=true;this.is_ie=true;}
if(navigator.userAgent.indexOf("MSIE 10.0")>-1){this.html_jquery_obj.addClass("ie10");this.is_ie10=true;this.is_ie=true;}
if(!!navigator.userAgent.match(/Trident.*rv\:11\./)){this.html_jquery_obj.addClass("ie11");this.is_ie11=true;}
if(window.history&&window.history.pushState){this.has_history=true;}
if(navigator.userAgent.indexOf('Safari')!=-1&&navigator.userAgent.indexOf('Chrome')==-1){this.is_safari=true;}
this.is_chrome=/chrom(e|ium)/.test(navigator.userAgent.toLowerCase());this.is_ipad=navigator.userAgent.match(/iPad/i)!=null;if(/(iPad|iPhone|iPod)/g.test(navigator.userAgent)){this.html_jquery_obj.addClass('md_detect_is_ios');this.is_ios=true;}else{this.is_ios=false;}
if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){this.is_mobile_device=true;}
this.run_is_phone_screen=function(){if((($(window).width()<768)||($(window).height()<640))&&(this.is_ipad===false)){this.is_phone_screen=true;}else{this.is_phone_screen=false;}};this.run_is_phone_screen();var user_agent=navigator.userAgent.toLowerCase();if(user_agent.indexOf("android")>-1){this.is_android=true;this.html_jquery_obj.addClass('md_detect_is_android');}
if(navigator.userAgent.indexOf('Mac OS X')!=-1){this.is_osx=true;}
if(navigator.userAgent.indexOf('Firefox')!=-1){this.is_firefox=true;}};var smartAffix={staticMenuSelector:'',fixedMenuSelector:'',menuHeight:0,menuOffsetTop:0,hasAdminBar:false,adminBarOffset:0,isAffixed:false,isShown:false,isFromInitial:false,windowScrollTop:0,lastWindowScrollTop:0,offCheckpoint:0,onCheckpoint:0,init:function init(options){smartAffix.fixedMenuSelector=options.fixedMenuSelector;smartAffix.staticMenuSelector=options.staticMenuSelector;smartAffix.hasAdminBar=options.hasAdminBar;if(!$(smartAffix.fixedMenuSelector).length){return;}
if(smartAffix.hasAdminBar){var screenWidth=$(window).width();if(screenWidth<600){smartAffix.adminBarOffset=0;}else if(screenWidth<782){smartAffix.adminBarOffset=46;}else{smartAffix.adminBarOffset=32;}}
if(Detect.is_firefox){smartAffix.compute();}
$(document).ready(function(){smartAffix.compute();});$(window).load(function(){smartAffix.compute();setTimeout(function(){smartAffix.compute();},1000);smartAffix.updateState();});},compute:function compute(){smartAffix.offCheckpoint=$(smartAffix.staticMenuSelector).offset().top-smartAffix.adminBarOffset;smartAffix.onCheckpoint=smartAffix.offCheckpoint+400;smartAffix.windowScrollTop=$(window).scrollTop();if(smartAffix.offCheckpoint<smartAffix.windowScrollTop){smartAffix.isAffixed=true;}
if(smartAffix.hasAdminBar){var screenWidth=$(window).width();if(screenWidth<600){smartAffix.adminBarOffset=0;}else if(screenWidth<782){smartAffix.adminBarOffset=46;}else{smartAffix.adminBarOffset=32;}}},updateState:function updateState(){if(smartAffix.isAffixed){$(smartAffix.fixedMenuSelector).addClass('mdAffixed');}else{$(smartAffix.fixedMenuSelector).removeClass('mdAffixed');}
if(smartAffix.isShown){$(smartAffix.fixedMenuSelector).addClass('mdAffixed--shown');}else{$(smartAffix.fixedMenuSelector).removeClass('mdAffixed--shown');}},eventScroll:function eventScroll(scrollTop){var scrollDirection='';var scrollDelta=0;if(scrollTop!=smartAffix.lastWindowScrollTop){if(scrollTop>smartAffix.lastWindowScrollTop){scrollDirection='down';}else{scrollDirection='up';}
scrollDelta=Math.abs(scrollTop-smartAffix.lastWindowScrollTop);smartAffix.lastWindowScrollTop=scrollTop;if(smartAffix.offCheckpoint<scrollTop){smartAffix.isAffixed=true;}else{smartAffix.isAffixed=false;}
if(smartAffix.isAffixed){if((scrollDirection=='down')&&(scrollDelta>10)){if(smartAffix.isShown){smartAffix.isShown=false;}}else{if((!smartAffix.isShown)&&(scrollDelta>10)&&(smartAffix.onCheckpoint<scrollTop)){smartAffix.isShown=true;}}}else{smartAffix.isShown=false;}
smartAffix.updateState();}},}
var smartAffixOn=Util.getBackendVar('stickyHeader','toggle');if(smartAffixOn=='1'){smartAffix.init({fixedMenuSelector:'.js-fixedHeader',staticMenuSelector:'.siteHeader-nav',hasAdminBar:Util.getBackendVar('stickyHeader','hasAdminBar'),});}
function BillboardParallax(){if(Detect.is_ie||Detect.is_touch_device||Detect.is_phone_screen){return;}
if($('.is-parallaxDisabled').length>0){return;}
var md_parallax_viewport=$('.postSingle--billboard-cover');var md_parallax_el=document.getElementById('md-billboard-info');var md_parallax_bg_el=document.getElementById('md-single-cover');if((md_parallax_el==null)||(!md_parallax_bg_el==null)){return;}
var on_checkpoint=$('.postSingle--billboard-cover').offset().top-$(window).height();if(on_checkpoint<0){on_checkpoint=0;}
var off_checkpoint=$('.postSingle--billboard-cover').offset().top+$('.postSingle--billboard-cover').height();var parallax_viewport_height=md_parallax_viewport.height();var bg_height=$(md_parallax_bg_el).height();var bg_offset=bg_height-parallax_viewport_height;var distanceToUpperEdge=1;if($(window).height()<=md_parallax_viewport.offset().top){distanceToUpperEdge=$(window).height();}else{distanceToUpperEdge=md_parallax_viewport.offset().top;}
var bg_translate_speed=bg_offset/distanceToUpperEdge;if(bg_translate_speed>0.8){bg_translate_speed=0.8;}
var on_checkpoint_text=$('#md-billboard-info').offset().top+0.5*($('#md-billboard-info').height()-$(window).height());if(on_checkpoint_text<0){on_checkpoint_text=0;}
var off_checkpoint_text=$('#md-billboard-info').offset().top+$('#md-billboard-info').height();var text_opacity_rate=0.6/(off_checkpoint_text-on_checkpoint_text);var scroll_from_top='';var distance_from_bottom;$(window).on('resize',function(){on_checkpoint=$('.postSingle--billboard-cover').offset().top-$(window).height();if(on_checkpoint<0){on_checkpoint=0;}
off_checkpoint=$('.postSingle--billboard-cover').offset().top+$('.postSingle--billboard-cover').height();parallax_viewport_height=md_parallax_viewport.height();bg_height=$(md_parallax_bg_el).height();bg_offset=bg_height-parallax_viewport_height;distanceToUpperEdge=1;if($(window).height()<=md_parallax_viewport.offset().top){distanceToUpperEdge=$(window).height();}else{distanceToUpperEdge=md_parallax_viewport.offset().top;}
bg_translate_speed=bg_offset/distanceToUpperEdge;if(bg_translate_speed>0.6){bg_translate_speed=0.6;}
on_checkpoint_text=$('#md-billboard-info').offset().top+0.5*($('#md-billboard-info').height()-$(window).height());if(on_checkpoint_text<0){on_checkpoint_text=0;}
off_checkpoint_text=$('#md-billboard-info').offset().top+$('#md-billboard-info').height();text_opacity_rate=0.6/(off_checkpoint_text-on_checkpoint_text);});$(window).scroll(function(){md_request_tick();});var md_animation_running=false;function md_request_tick(){if(md_animation_running===false){window.requestAnimationFrame(md_do_animation);}
md_animation_running=true;}
function md_do_animation(){scroll_from_top=$(document).scrollTop();if((scroll_from_top<=off_checkpoint)&&(scroll_from_top>=on_checkpoint)){var scroll_distance=scroll_from_top-on_checkpoint;var parallax_move=-Math.round(scroll_distance*bg_translate_speed);Util.moveY(md_parallax_bg_el,-parallax_move);}
if((scroll_from_top<off_checkpoint_text)&&(scroll_from_top>on_checkpoint_text)){var scroll_distance=scroll_from_top-on_checkpoint_text;var blur_value=1-(scroll_distance*text_opacity_rate);blur_value=Math.round(blur_value*100)/100;if(Detect.is_ie8===true){blur_value=1;}
md_parallax_el.style.opacity=blur_value;}else if(scroll_from_top<=on_checkpoint_text){md_parallax_el.style.opacity=1;}
md_animation_running=false;}}
$(document).ready(function(){BillboardParallax();})
function md_gallery_slider(selector){$(selector).fotorama();}
$(window).load(function(){if($.isFunction($.fn.masonry)){var $masonryGrid=$('.js-masonry-grid');$masonryGrid.masonry({itemSelector:'.grid-item'});}});function md_ajaxLoadPosts(){if(!$('.js-ajax-loadmore.is-active').length){return;}
var pageNum=parseInt(Util.getBackendVar('ajaxloadpost','startPage'));var max=parseInt(Util.getBackendVar('ajaxloadpost','maxPages'));var loadedPosts='';var ajaxStatus='';ajaxLoadPosts($('.js-ajax-loadmore.is-active'));$(document).on('click','.js-ajax-loadmore.is-active',function(){appendResponse($(this));ajaxLoadPosts($(this));})
function ajaxLoadPosts(loadBtn){if(pageNum<max){var loadedPostsCount=loadBtn.siblings('#mdContent').find('article').length;loadBtn.removeClass('is-active');var ajaxCall=$.ajax({url:Util.getBackendVar('ajaxloadpost','ajaxurl'),type:'post',data:{action:'ajax_load_post',query_vars:Util.getBackendVar('ajaxloadpost','query_vars'),page:pageNum+1,loadedPostsCount:loadedPostsCount,currentRelURI:Util.getBackendVar('currentRelURI'),}})
ajaxCall.done(function(respond){loadedPosts=$(respond);ajaxStatus='success';});ajaxCall.fail(function(){ajaxStatus='failed';});ajaxCall.always(function(){updateBtnText(loadBtn);pageNum++;})}}
function addThisReload(){if(typeof addthis!=='undefined'){addthis.toolbox('.addthis_toolbox');addthis.counter('.addthis_counter');addthis.ready();}}
function appendResponse(loadBtn){loadBtn.removeClass('is-active');if($('#mdContent').hasClass('js-masonry-grid')){$("#mdContent").append(loadedPosts).masonry('appended',loadedPosts,true);}else{$(loadedPosts).appendTo('#mdContent').css('opacity',0).animate({opacity:1},500);}
md_gallery_slider('#mdContent .fotorama');addThisReload();updateBtnText(loadBtn);$('html, body').animate({scrollTop:$(window).scrollTop()+1},0);loadedPosts='';}
function updateBtnText(loadBtn){if(ajaxStatus=='failed'){loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','failText'));}else{if(pageNum>=max){loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','noMoreText'));}else{loadBtn.addClass('is-active');}}}}
$(document).ready(function(){md_ajaxLoadPosts();})
function md_ajaxIfninityScroll(){var loadBtn=$('.js-ajax-infinity-scroll.is-active');if(!loadBtn.length){return;}
var pageNum=parseInt(Util.getBackendVar('ajaxloadpost','startPage'));var max=parseInt(Util.getBackendVar('ajaxloadpost','maxPages'));var initialText=loadBtn.text();function updateBtn(){if(pageNum==max){loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','noMoreText'));}else{loadBtn.find('span').text(initialText);loadBtn.addClass('is-active');}
return $(this);}
function addThisReload(){if(typeof addthis!=='undefined'){addthis.toolbox('.addthis_toolbox');addthis.counter('.addthis_counter');addthis.ready();}}
function ajaxLoadPosts(){if(pageNum<max){var loadedPostsCount=loadBtn.siblings('#mdContent').find('article').length;loadBtn.addClass('is-loading');loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','loadingText'));loadBtn.find('i').addClass('fa-spin');var ajaxCall=$.ajax({url:Util.getBackendVar('ajaxloadpost','ajaxurl'),type:'post',data:{action:'ajax_load_post',query_vars:Util.getBackendVar('ajaxloadpost','query_vars'),page:pageNum+1,loadedPostsCount:loadedPostsCount,currentRelURI:Util.getBackendVar('currentRelURI'),}});ajaxCall.done(function(respond){var html=$(respond);if($('#mdContent').hasClass('js-masonry-grid')){$("#mdContent").append(html).masonry('appended',html,true);}else{$(html).appendTo('#mdContent').css('opacity',0).animate({opacity:1},500);}
md_gallery_slider('#mdContent .fotorama');addThisReload();$('html, body').animate({scrollTop:$(window).scrollTop()+1},0);updateBtn();pageNum++;});ajaxCall.fail(function(){loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','failText'));});ajaxCall.always(function(){loadBtn.removeClass('is-loading');loadBtn.find('i').removeClass('fa-spin');});}else{loadBtn.find('span').text(Util.getBackendVar('ajaxloadpost','noMoreText'));}}
function ajaxScrollEvent(){if(loadBtn.length){if((loadBtn.offset().top-$(window).scrollTop()-$(window).height())<=$(window).height()*3){if(loadBtn.hasClass('is-active')){loadBtn.removeClass('is-active');ajaxLoadPosts();}}}}
$(window).scroll(ajaxScrollEvent);}
$(document).ready(function(){md_ajaxIfninityScroll();});function hiDPI(){var hidpi='',mediaQuery="(-webkit-min-device-pixel-ratio: 1.5),(min--moz-device-pixel-ratio: 1.5),(-o-min-device-pixel-ratio: 3/2),(min-resolution: 1.5dppx)";if(window.devicePixelRatio>1){hidpi=true;}
if(window.matchMedia&&window.matchMedia(mediaQuery).matches){hidpi=true;}
if(hidpi){var $logos=$('.siteLogo--image img');$logos.each(function(){if($(this).is('[data-hidpi]')){var src=$(this).attr('data-hidpi');$(this).attr('src',src);}});$('.o-backgroundImg, .u-hasBackgroundImg, #md-single-cover').each(function(){if($(this).is('[data-hidpi]')){var src=$(this).attr('data-hidpi');$(this).css('background-image','url('+src+')');}});}}
$(document).ready(function(){if(Util.getBackendVar('highResolution')=='1'){hiDPI();}});$(function(){$(document).ready(function(){$('.js-popover-toggle').click(function(e){e.stopPropagation();$('.js-popover.is-active').toggleClass('is-active');$(this).siblings('.js-popover').toggleClass('is-active');});$('.js-popover').click(function(e){e.stopPropagation();});$(document).on("click",function(){$('.js-popover').removeClass('is-active');});$('.js-userActions-btn').click(function(e){e.stopPropagation();$(this).siblings('.userActions-popup').toggleClass('is-active');});$('.js-userActions-popup').click(function(e){e.stopPropagation();});$(document).on("click",function(){$('.js-userActions-popup').removeClass('is-active');});$('.js-searchToggle').on('click',function(e){e.stopPropagation();$(this).toggleClass('isActive');$(this).siblings('.js-searchToggle').toggleClass('isActive');$(this).closest('.js-searchOuter').toggleClass('isSearchActive');$(this).closest('.js-searchOuter.isSearchActive').find('.searchField-form-input').focus();});$('.js-searchToggle').siblings('.searchField').click(function(e){e.stopPropagation();})
$(document).on("click",function(){$('.js-searchToggle').removeClass('isActive').closest('.siteHeader-nav').removeClass('isSearchActive');});if(typeof addthis!=='undefined'){addthis.init();}
if(Util.getBackendVar('stickySidebar','toggle')==='1'){$('.js-sticky-sidebar').theiaStickySidebar({additionalMarginTop:Util.getBackendVar('stickySidebar','offsetTop'),additionalMarginBottom:40});}
$('.widget_nav_menu .menu > li.menu-item-has-children').append(function(){return $('<div class="submenu-toggle"><i class="fa fa-angle-down"></i></div>').click(function(){$(this).parent().children('.sub-menu').slideToggle(200);});});var $featCarousel=$('.js-feat-carousel');$featCarousel.owlCarousel({items:3,dots:false,nav:true,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],margin:20,loop:false,smartSpeed:500,responsive:{0:{items:1,dots:true,nav:false,},768:{items:2,dots:false,},992:{items:3,dots:false,},1200:{items:3,dots:false,},}});var $featSlider=$('.js-feat-slider-peek');var autoplay=Util.getBackendVar('sliderOpts','autoplay');var timeout=Util.getBackendVar('sliderOpts','timeout');$featSlider.owlCarousel({items:1,dots:true,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],margin:20,autoplay:autoplay,autoplayTimeout:timeout,autoplayHoverPause:true,loop:true,smartSpeed:500,responsive:{0:{margin:0,nav:false,},768:{margin:20,nav:true,},}});var $featSliderFw=$('.js-feat-slider');$featSliderFw.owlCarousel({items:1,dots:true,autoplay:autoplay,autoplayTimeout:timeout,autoplayHoverPause:true,loop:true,smartSpeed:500,});$('.js-slider-widget').owlCarousel({items:1,dots:true,nav:false,});if($('.js-scrolltop-btn').length){$('.js-scrolltop-btn').on('click',function(){$('html, body').animate({scrollTop:0},500);});}
$('.js-menu-toggle').click(function(){$('#md_offCanvasMenu').addClass('is-opened');if($('#md_canvasOverlay').length===0){var overlay=$('<div id="md_canvasOverlay" class="is-active"></div>');overlay.click(function(){$('#md_offCanvasMenu').removeClass('is-opened');$('#mdSidebar').removeClass('is-opened');$(this).removeClass('is-active');$('body').removeClass('has-md-offcanvas-opened');});$('body').append(overlay).addClass('has-md-offcanvas-opened');}else{$('#md_canvasOverlay').addClass('is-active');$('body').addClass('has-md-offcanvas-opened');}});$('.js-offCanvasClose').click(function(){$(this).parents('.md_offCanvas').removeClass('is-opened');$('#md_canvasOverlay').removeClass('is-active');$('body').removeClass('has-md-offcanvas-opened');});function toggleSubMenu($toggleBtn){$toggleBtn.find('i').toggleClass('fa-angle-left');$toggleBtn.find('i').toggleClass('fa-angle-down');$toggleBtn.parent('a').siblings('.sub-menu').slideToggle(200);}
var subMenuToggle=$('<div class="subMenuToggle"><i class="fa fa-angle-down"></i></div>');subMenuToggle.click(function(e){e.preventDefault();e.stopPropagation();toggleSubMenu($(this));});$('#md_offCanvasMenu').find('li.menu-item-has-children > a').append(subMenuToggle);var offcanvasMenuItems=$('.md_offCanvasMenu-navigation').find('ul.menu > .menu-item-has-children');offcanvasMenuItems.each(function(i,menuItem){var $menuItem=$(menuItem);if(($menuItem.children('a').length===0)||($menuItem.children('a[href^="#"]').length!==0)){$menuItem.children('a').click(function(e){e.preventDefault();toggleSubMenu($menuItem.find('.subMenuToggle'));});}});$('.js-imageZoom','.postContent').attr('data-action','zoom');});});}(window.mdBone=window.mdBone||{},jQuery));